### PR TITLE
Update readme, link to MSFT azure-functions-cli

### PR DESCRIPTION
**Pull request by lindydonna**
I removed the png, so that it doesn't look like an official package.

### CODE REVIEW

**Comment by sedouard** [comment]
👍

**Comment by lindydonna** [comment]
Thanks for the speedy merge!  Let me know when you've updated the package.

**Comment by sedouard** [comment]
done! also fyi - you should consider filling out the metadata in the `package.json` for `azure-functions-cli`. Currently it has no issue link, website link, repo, maintainer listed (even though it is marked MIT).

**Comment by lindydonna** [comment]
Oh, good catch!  Will definitely follow up on that.

**Pull request merged**
